import type { ProjectCategory, ProjectDefinition } from "@/types";

export const PROJECT_LIST: Record<ProjectCategory, ProjectDefinition[]> = {
    showcase: [
        {
            name: "Nova",
            description: "A modern, lightweight Point of Sale (POS) application.",
            framework: ["Tauri", "React", "TypeScript", "Tailwind", "shadcn/ui", "SQLite", "Postgres"],
        },
        {
            name: "Personal Blog CMS",
            description: "A simple yet modern front-end dashboard for managing my blog posts and readers’ comments.",
            framework: ["React", "TypeScript", "React Router", "TanStack Query", "Tailwind", "shadcn/ui", "TipTap", "localForage"],
            source: "https://github.com/mkgp-dev/blog-cms",
            link: "https://mkgp-blog.pages.dev"
        },
        {
            name: "Personal Blog CMS API",
            description: "API-only backend for my personal blog system.",
            framework: ["Node.js", "Express", "TypeScript", "Prisma", "jsonwebtoken", "Zod", "Pino"],
            source: "https://github.com/mkgp-dev/blog-cms-api",
        },
        {
            name: "Resume Makinator",
            description: "A modern, browser-based tool that helps anyone create a polished resume.",
            framework: ["React", "Tailwind", "DaisyUI", "Zustand", "localForage", "react-pdf", "dndkit"],
            source: "https://github.com/mkgp-dev/resume-makinator",
            link: "https://resume-makinator.pages.dev"
        },
        {
            name: "Ship Wreck",
            description: "A simple Battleship project.",
            framework: ["Webpack", "Tailwind", "Jest"],
            source: "https://github.com/mkgp-dev/ship-wreck",
            link: "https://mkgp-dev.github.io/ship-wreck",
        },
        {
            name: "Forecast Me",
            description: "A simple Weather App project.",
            framework: ["Webpack", "Tailwind"],
            source: "https://github.com/mkgp-dev/forecast-me",
            link: "https://mkgp-dev.github.io/forecast-me",
        },
        {
            name: "Public Backend",
            description: "Personal API gateway for my projects.",
            framework: ["Upstash", "Axios", "Vercel"],
            source: "https://github.com/mkgp-dev/public-backend",
            link: "https://mkgpdev-backend.vercel.app",
        },
        {
            name: "What to do",
            description: "A simple To-Do List project.",
            framework: ["Webpack", "Tailwind", "localForage"],
            source: "https://github.com/mkgp-dev/what-to-do",
            link: "https://mkgp-dev.github.io/what-to-do",
        },
        {
            name: "Hard Licker",
            description: "A simple Restaurant Page project.",
            framework: ["Webpack", "CSS"],
            source: "https://github.com/mkgp-dev/personal-top-archive/blob/main/restaurant-page/open-source",
            link: "https://mkgp-dev.github.io/personal-top-archive/restaurant-page",
        },
        {
            name: "Blog Portfolio PHP",
            description: "Blog PHP integrated with your portfolio.",
            framework: ["PHP", "HTML", "JavaScript", "jQuery", "Bootstrap"],
            source: "https://github.com/mkgp-dev/Blog-Portfolio-PHP",
        },
    ],
    top: [
        {
            name: "Droppy",
            description: "A simple File Uploader project.",
            framework: ["Node.js", "Express", "TypeScript", "Tailwind", "Prisma", "Postgres", "Passport", "Multer"],
            source: "https://github.com/mkgp-dev/droppy",
            link: "https://droppy.up.railway.app",
        },
        {
            name: "Message Wall Membership",
            description: "A simple Members Only project.",
            framework: ["Node.js", "Express", "TypeScript", "Tailwind", "DaisyUI", "Postgres", "Passport"],
            source: "https://github.com/mkgp-dev/message-wall-membership",
            link: "https://message-wall-membership.up.railway.app",
        },
        {
            name: "Playtory",
            description: "A simple Inventory Application project.",
            framework: ["Node.js", "Express", "TypeScript", "Tailwind", "DaisyUI", "Postgres"],
            source: "https://github.com/mkgp-dev/playtory",
            link: "https://playtory.up.railway.app",
        },
        {
            name: "Message Wall",
            description: "A simple Mini Message Board project.",
            framework: ["Node.js", "Express", "TypeScript", "Tailwind", "DaisyUI", "nanoid"],
            source: "https://github.com/mkgp-dev/message-wall",
            link: "https://message-wall.up.railway.app",
        },
        {
            name: "Shople",
            description: "A simple Shopping Cart project.",
            framework: ["React", "TypeScript", "Tailwind", "shadcn/ui", "Vitest", "Zustand", "React Router"],
            source: "https://github.com/mkgp-dev/shople",
            link: "https://shople.netlify.app",
        },
        {
            name: "Memoire",
            description: "A simple Memory Card project.",
            framework: ["React", "TypeScript", "Tailwind", "shadcn/ui", "Motion", "Zustand", "localForage"],
            source: "https://github.com/mkgp-dev/memoire",
            link: "https://memoire-mkgpdev.netlify.app",
        },
        {
            name: "Unofficial Portfolio",
            description: "A simple Homepage project.",
            framework: ["Webpack", "Tailwind"],
            source: "https://github.com/mkgp-dev/unofficial-portfolio",
            link: "https://mkgp-dev.github.io/unofficial-portfolio",
        },
        {
            name: "Tic Tac Toe",
            description: "A simple Tic Tac Toe project.",
            framework: ["HTML", "JavaScript", "CSS"],
            source: "https://github.com/mkgp-dev/personal-top-archive/blob/main/tic-tac-toe",
            link: "https://mkgp-dev.github.io/personal-top-archive/tic-tac-toe",
        },
        {
            name: "Library",
            description: "A simple Library project.",
            framework: ["HTML", "JavaScript", "CSS"],
            source: "https://github.com/mkgp-dev/personal-top-archive/tree/main/library",
            link: "https://mkgp-dev.github.io/personal-top-archive/library",
        },
        {
            name: "Admin Dashboard",
            description: "A simple Admin Dashboard project.",
            framework: ["HTML", "CSS"],
            source: "https://github.com/mkgp-dev/personal-top-archive/tree/main/admin-dashboard",
            link: "https://mkgp-dev.github.io/personal-top-archive/admin-dashboard",
        },
        {
            name: "Sign-up Form",
            description: "A simple Sign-up Form project.",
            framework: ["HTML", "CSS"],
            source: "https://github.com/mkgp-dev/personal-top-archive/tree/main/sign-up-form",
            link: "https://mkgp-dev.github.io/personal-top-archive/sign-up-form",
        },
        {
            name: "Calculator",
            description: "A simple Calculator project.",
            framework: ["HTML", "JavaScript", "CSS"],
            source: "https://github.com/mkgp-dev/personal-top-archive/tree/main/calculator",
            link: "https://mkgp-dev.github.io/personal-top-archive/calculator",
        },
        {
            name: "Etch a Sketch",
            description: "A simple Etch a Sketch project.",
            framework: ["HTML", "JavaScript", "CSS"],
            source: "https://github.com/mkgp-dev/personal-top-archive/tree/main/etch-a-sketch",
            link: "https://mkgp-dev.github.io/personal-top-archive/etch-a-sketch",
        },
        {
            name: "Rock Paper Scissors",
            description: "A simple Rock Paper Scissors project.",
            framework: ["HTML", "JavaScript", "CSS"],
            source: "https://github.com/mkgp-dev/personal-top-archive/tree/main/rock-paper-scissors",
            link: "https://mkgp-dev.github.io/personal-top-archive/rock-paper-scissors",
        },
        {
            name: "Landing Page",
            description: "A simple Landing Page project.",
            framework: ["HTML", "CSS"],
            source: "https://github.com/mkgp-dev/personal-top-archive/tree/main/landing-page",
            link: "https://mkgp-dev.github.io/personal-top-archive/landing-page",
        },
        {
            name: "Landing Page",
            description: "A simple Landing Page project.",
            framework: ["HTML", "CSS"],
            source: "https://github.com/mkgp-dev/personal-top-archive/tree/main/landing-page",
            link: "https://mkgp-dev.github.io/personal-top-archive/landing-page",
        },
        {
            name: "Recipe",
            description: "A simple Recipe project.",
            framework: ["HTML"],
            source: "https://github.com/mkgp-dev/personal-top-archive/blob/main/odin-recipes",
            link: "https://mkgp-dev.github.io/personal-top-archive/odin-recipes",
        },
    ],
    fcc: [
        {
            name: "25 + 5 Clock",
            framework: ["React", "Bootstrap"],
            link: "https://codepen.io/mkgp-dev/full/yyeVRvM",
        },
        {
            name: "JavaScript Calculator",
            framework: ["React", "Bootstrap"],
            link: "https://codepen.io/mkgp-dev/full/jEWVWGj",
        },
        {
            name: "Drum Machine",
            framework: ["React", "Bootstrap"],
            link: "https://codepen.io/mkgp-dev/full/EaPgXyB",
        },
        {
            name: "Markdown Previewer",
            framework: ["React", "Bootstrap"],
            link: "https://codepen.io/mkgp-dev/full/EaPgXyB",
        },
        {
            name: "Random Quote Machine",
            framework: ["React", "Bootstrap"],
            link: "https://codepen.io/mkgp-dev/full/JoGKdEz",
        },
        {
            name: "freeCodeCamp Back End",
            description: "A certificate project from freeCodeCamp, whereas every single objective from Back End Development and APIs are compiled into one.",
            framework: ["Node.js", "Express", "MongoDB", "Multer"],
            source: "https://github.com/mkgp-dev/freeCodeCamp-Back-End",
            link: "https://freecodecamp-backend-u2c9.onrender.com",
        },
        {
            name: "Personal Portfolio Webpage",
            framework: ["HTML", "CSS"],
            link: "https://codepen.io/mkgp-dev/full/jEWVbJQ",
        },
        {
            name: "Product Landing Page",
            framework: ["HTML", "CSS"],
            link: "https://codepen.io/mkgp-dev/full/KwVNdbr",
        },
        {
            name: "Technical Documentation Page",
            framework: ["HTML", "CSS"],
            link: "https://codepen.io/mkgp-dev/full/XJXNmxv",
        },
        {
            name: "Tribute Page",
            framework: ["HTML", "CSS"],
            link: "https://codepen.io/mkgp-dev/full/zxrovLg",
        },
        {
            name: "Survey Form",
            framework: ["HTML", "CSS"],
            link: "https://codepen.io/mkgp-dev/full/OPMbywO",
        },
    ],
};